[TH-4] 2022 April token listing
bit-oasis/coin pull request #27
Opened 2022-04-13 08:50 UTC by RobMKR

2022-04-25 08:56 UTC, jalal-omari-bo approved these changes

2022-04-25 18:04 UTC, foowie requested changes
> Reviewed 86 of 86 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bit-oasis/coin/27)* status: all files reviewed, 4 unresolved discussions (waiting on @RobMKR)

___
*[`src/BitOasis/Coin/Address/IotaAddress.php` line 19 at r1](https://reviewable.io/reviews/bit-oasis/coin/27#-N0WqlMG5maMx8zqA2Nk:-N0WqlMG5maMx8zqA2Nl:bqq7yf7) ([raw file](https://github.com/bit-oasis/coin/blob/eaa667e099729540a6813baacfaae7cda019d740/src/BitOasis/Coin/Address/IotaAddress.php#L19)):*
> ```PHP
> 	 */
> 	protected function createValidator($address, $tag = null) {
> 		return new IotaAddressValidator($address);
> ```

Either you missed tag or iota does not have tag (and then BaseBench32Address implementation should be split)
___
*[`src/BitOasis/Coin/Address/Validators/DigibyteAddressValidator.php` line 14 at r1](https://reviewable.io/reviews/bit-oasis/coin/27#-N0WrdnG8zyjyCzPcmDz:-N0WrdnG8zyjyCzPcmE-:b-mnguht) ([raw file](https://github.com/bit-oasis/coin/blob/eaa667e099729540a6813baacfaae7cda019d740/src/BitOasis/Coin/Address/Validators/DigibyteAddressValidator.php#L14)):*
> ```PHP
> 	protected $base58PrefixToHexVersion = [
> 		// Supporting only legacy addresses
>         'D' => '1e'
> ```

Is this agreed? What is the reason not to support new?
___
*[`src/BitOasis/Coin/Address/Validators/ElrondEgoldValidator.php` line 12 at r1](https://reviewable.io/reviews/bit-oasis/coin/27#-N0Wrugj-8WUGXLeIGE6:-N0Wrugj-8WUGXLeIGE7:bwf5yiy) ([raw file](https://github.com/bit-oasis/coin/blob/eaa667e099729540a6813baacfaae7cda019d740/src/BitOasis/Coin/Address/Validators/ElrondEgoldValidator.php#L12)):*
> ```PHP
> class ElrondEgoldValidator extends Bech32AddressValidator implements ValidationInterface {
> 
> 	protected $prefix = 'erd';
> ```

This redefinition of variable just to set default value can be done in a better way. Like constructor. (but keep it as is)
___
*[`tests/unit/BitOasis/Coin/Address/DigibyteAddressTest.php` line 27 at r1](https://reviewable.io/reviews/bit-oasis/coin/27#-N0WsyqECn4iOr68Z4gP:-N0WsyqECn4iOr68Z4gQ:bk5e273) ([raw file](https://github.com/bit-oasis/coin/blob/eaa667e099729540a6813baacfaae7cda019d740/tests/unit/BitOasis/Coin/Address/DigibyteAddressTest.php#L27)):*
> ```PHP
> 	public function providerInvalidAddress() {
> 		return [
> 			['AKgXqynY4y82dYqSoC4Bt77A3qYKEg7fq4'],
> ```

You can add new format here with comment that its just not supported


<!-- Sent from Reviewable.io -->

2022-04-26 06:31 UTC, RobMKR reviewed
> *[Reviewable](https://reviewable.io/reviews/bit-oasis/coin/27)* status: all files reviewed, 4 unresolved discussions (waiting on @foowie)

___
*[`src/BitOasis/Coin/Address/IotaAddress.php` line 19 at r1](https://reviewable.io/reviews/bit-oasis/coin/27#-N0WqlMG5maMx8zqA2Nk:-N0ZXTCH8e2-Musz9x0Q:bco2pdm) ([raw file](https://github.com/bit-oasis/coin/blob/eaa667e099729540a6813baacfaae7cda019d740/src/BitOasis/Coin/Address/IotaAddress.php#L19)):*
<details><summary><i>Previously, foowie (Daniel Robenek) wrote…</i></summary><blockquote>

Either you missed tag or iota does not have tag (and then BaseBench32Address implementation should be split)
</blockquote></details>

Iota doesn't  support, so splited into 2 classes
___
*[`src/BitOasis/Coin/Address/Validators/DigibyteAddressValidator.php` line 14 at r1](https://reviewable.io/reviews/bit-oasis/coin/27#-N0WrdnG8zyjyCzPcmDz:-N0ZPMdv1-CBJ2pN3_vV:b-cxo6r8) ([raw file](https://github.com/bit-oasis/coin/blob/eaa667e099729540a6813baacfaae7cda019d740/src/BitOasis/Coin/Address/Validators/DigibyteAddressValidator.php#L14)):*
<details><summary><i>Previously, foowie (Daniel Robenek) wrote…</i></summary><blockquote>

Is this agreed? What is the reason not to support new?
</blockquote></details>

Agreed with Francesco. But I found the richlist of Digibyte, and seems all the types are widely used. Most probably best to support them now.
___
*[`src/BitOasis/Coin/Address/Validators/ElrondEgoldValidator.php` line 12 at r1](https://reviewable.io/reviews/bit-oasis/coin/27#-N0Wrugj-8WUGXLeIGE6:-N0ZVJf-EWmJuByA50dY:b3qkqjs) ([raw file](https://github.com/bit-oasis/coin/blob/eaa667e099729540a6813baacfaae7cda019d740/src/BitOasis/Coin/Address/Validators/ElrondEgoldValidator.php#L12)):*
<details><summary><i>Previously, foowie (Daniel Robenek) wrote…</i></summary><blockquote>

This redefinition of variable just to set default value can be done in a better way. Like constructor. (but keep it as is)
</blockquote></details>

Refactored ;)
___
*[`tests/unit/BitOasis/Coin/Address/DigibyteAddressTest.php` line 27 at r1](https://reviewable.io/reviews/bit-oasis/coin/27#-N0WsyqECn4iOr68Z4gP:-N0ZQ75pBWOSSWB-Up5z:b3pm26f) ([raw file](https://github.com/bit-oasis/coin/blob/eaa667e099729540a6813baacfaae7cda019d740/tests/unit/BitOasis/Coin/Address/DigibyteAddressTest.php#L27)):*
<details><summary><i>Previously, foowie (Daniel Robenek) wrote…</i></summary><blockquote>

You can add new format here with comment that its just not supported
</blockquote></details>

Should be implemented all types.


<!-- Sent from Reviewable.io -->

2022-04-26 08:02 UTC, foowie approved these changes
> Reviewed 15 of 15 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bit-oasis/coin/27)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jalal-omari-bo)



<!-- Sent from Reviewable.io -->

2022-04-26 08:04 UTC, merged